<a href="https://colab.research.google.com/github/Ashvaneemishra322/collab-notebooks/blob/main/panda_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas question

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = [
    ['Aman' , 20 , 85],
    ['Ravi' , 19 , 90],
    ['Sita' , 21 , 88]
]
column = ['Name' , 'Age' , 'Marks']
df = pd.DataFrame(data , columns = column)
df

   Name  Age  Marks
0  Aman   20     85
1  Ravi   19     90
2  Sita   21     88

In [ ]:
df['Age']

0    20
1    19
2    21
Name: Age, dtype: int64

In [ ]:
df.loc[[0,1]]

   Name  Age  Marks
0  Aman   20     85
1  Ravi   19     90

In [ ]:
df.loc[[1]]

   Name  Age  Marks
1  Ravi   19     90

In [ ]:
# # df["Passed"] = df["Marks"].apply(lambda x: "Yes" if (x >= 40) else "No")
# df["Passed"] = df["Marks"] >= 40
# df["Passed"] = df["Passed"].map({True:"Yes", False:"No"})
df["Marks"] = df["Marks"].astype(int)

df["Passed"] = df["Marks"].apply(lambda x: "Yes" if x >= 40 else "No")

In [ ]:
# df['Marks'] = df['Marks'].astype(int)
# df[df["Marks"] >= 40]

In [ ]:
# df["gkp"] = ["d","d","d"]

In [ ]:

df

   Name  Age  Marks
0  Aman   20     85
1  Ravi   19     90
2  Sita   21     88

In [ ]:
# Find average marks
# Find maximum marks
# Find minimum marks

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())

87.66666666666667
90
85

second

In [ ]:
data = [
    ['Aman' , 20 , 85],
    ['Ravi' , 19 , 32],
    ['Sita' , 21 , 88],
    ['Karan', 22 , 45]
]
column = ['Name' , 'Age' , 'Marks']
df2 = pd.DataFrame(data , columns = column)
df2

    Name  Age  Marks
0   Aman   20     85
1   Ravi   19     32
2   Sita   21     88
3  Karan   22     45

In [ ]:
# Show students with Marks > 50
# Show students with Age > 20
df2[(df2['Marks'] > 50) & (df2['Age'] > 20)]

# df2[df2['Marks'] > 50]

   Name  Age  Marks
2  Sita   21     88

In [ ]:
# df2[df2['Age'] > 20]

In [ ]:
# Sort the DataFrame:
# By Marks (descending)
# By Age (ascending)

df2.sort_values(by = 'Marks' , ascending=True)

    Name  Age  Marks
1   Ravi   19     32
3  Karan   22     45
0   Aman   20     85
2   Sita   21     88

In [ ]:
df2['City'] = ['Delhi' , 'Delhi' , 'Mumbai' , 'Delhi']

In [ ]:
df2

    Name  Age  Marks    City
0   Aman   20     85   Delhi
1   Ravi   19     32   Delhi
2   Sita   21     88  Mumbai
3  Karan   22     45   Delhi

In [ ]:
# Count how many students belong to each city.
# df2['City'].value_counts()
# df2.groupby("City").size()
df2.groupby("City").size().reset_index(name="Student_Count")

     City  Student_Count
0   Delhi              3
1  Mumbai              1

Third

In [ ]:
data = [
    ['IT' , 'HR' , 'IT' , 'HR' , 'IT'],
    [50000 , 40000 , 60000 , 45000 , 70000]
]

df3 = pd.DataFrame(data).T
df3.columns = ["Department" , "Sallary"]

In [ ]:
df3

  Department Sallary
0         IT   50000
1         HR   40000
2         IT   60000
3         HR   45000
4         IT   70000

In [ ]:
# Find average salary of each department
df3['Sallary'].mean()

np.float64(53000.0)

that que of missing value

In [ ]:
data = [
    ['Aman' , 'Ravi' , 'Sita'],
    [80 , np.nan , 90]
]
DF = pd.DataFrame(data).T
DF.columns = ['Name' , 'Marks']

In [ ]:
DF

   Name Marks
0  Aman    80
1  Ravi   NaN
2  Sita    90

In [ ]:
# Detect missing values
# Replace missing value with 0

DF.isnull().sum()
DF.fillna(0, inplace=True)

/tmp/ipykernel_6563/1338320788.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  DF.fillna(0, inplace=True)

In [ ]:
DF

   Name  Marks
0  Aman     80
1  Ravi      0
2  Sita     90

Apply

In [ ]:
data = [
    ['Aman' , 'Ravi' , 'Sita' , 'karan' , 'marry'],
    [45, 67, 82, 30, 55]
]
sam = pd.DataFrame(data).T
sam.columns = ['Name' , 'Marks']

In [ ]:
sam

    Name Marks
0   Aman    45
1   Ravi    67
2   Sita    82
3  karan    30
4  marry    55

In [ ]:
# Create a new column Grade

# Rules:

# ≥ 80 → A

# ≥ 60 → B

# ≥ 40 → C

# < 40 → Fail

###### create a function #######

def grade(mark):

  if (mark >= 80):
    return 'A'
  elif (mark >= 60):
    return 'B'
  elif (mark >= 40):
    return 'C'
  else:
    return 'Fail'

In [ ]:
sam['Grade'] = sam["Marks"].apply(grade)

In [ ]:
sam

    Name Marks Grade
0   Aman    45     C
1   Ravi    67     B
2   Sita    82     A
3  karan    30  Fail
4  marry    55     C

np.where(condition, true_value, false_value)

In [ ]:
df["Grade"] = np.where(df["Marks"]>=80,"A",
               np.where(df["Marks"]>=60,"B",
               np.where(df["Marks"]>=40,"C","Fail")))

In [ ]:
sam

    Name Marks Grade
0   Aman    45     C
1   Ravi    67     B
2   Sita    82     A
3  karan    30  Fail
4  marry    55     C